name: terraform

on:
  pull_request:
    paths: ['*.tf', 'modules/**', '.github/workflows/terraform.yml']
  push:
    branches: [main]
    paths: ['*.tf', 'modules/**', '.github/workflows/terraform.yml']

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4
        with: { terraform_version: 1.15.5 }
      # - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Trivy (IaC misconfig)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: config
          scan-ref: .
          skip-dirs: bootstrap
          severity: HIGH,CRITICAL
          exit-code: '1'
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          skip_path: bootstrap

  plan:
    needs: [validate, scan]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      TF_VAR_admin_user_arn: ${{ vars.ADMIN_USER_ARN }}
      TF_VAR_admin_cidr: ${{ vars.ADMIN_CIDR }}
      TF_VAR_github_owner: ${{ github.repository_owner }}
      TF_VAR_github_repo: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ vars.AWS_PLAN_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with: { terraform_version: 1.15.5 }
      - run: terraform init
      - run: terraform plan -no-color -lock=false

  apply:
    needs: [validate, scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_VAR_admin_user_arn: ${{ vars.ADMIN_USER_ARN }}
      TF_VAR_admin_cidr: ${{ vars.ADMIN_CIDR }}
      TF_VAR_github_owner: ${{ github.repository_owner }}
      TF_VAR_github_repo: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ vars.AWS_APPLY_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v4
        with: { terraform_version: 1.15.5 }
      - run: terraform init
      - run: terraform apply -auto-approve